services:
  - type: web
    name: map-scraper
    plan: free
    runtime: python
    python:
      version: 3.9.16
    buildCommand: pip install -r requirements.txt
    startCommand: python3 scraperMAP.py
